-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.

CREATE OR REPLACE TABLE `fund_ops`.`silver`.`parsed_docs` AS
WITH raw AS (
  SELECT _metadata.file_name AS file_name, ai_parse_document(content) AS parsed
  FROM read_files('/Volumes/fund_ops/raw/landing/', format => 'binaryFile')
)
SELECT
  file_name,
  CASE WHEN lower(file_name) rlike 'capital[-_ ]?call' THEN 'capital_call'
       ELSE 'distribution' END AS doc_type,
  concat_ws('\n', transform(cast(parsed:document:elements AS ARRAY<VARIANT>),
                             e -> e:content::string)) AS text,
  try_cast(parsed:error_status AS string) AS parse_error
FROM raw
