-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.

CREATE OR REPLACE TABLE `fund_ops`.`silver`.`doc_classification` AS
SELECT file_name, doc_type AS filename_type,
       ai_classify(text, array('capital_call','distribution','capital_account',
                               'subscription','lpa','other')) AS predicted_type
FROM `fund_ops`.`silver`.`parsed_docs`
