-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.

CREATE OR REPLACE TABLE `fund_ops`.`silver`.`capital_accounts` AS
SELECT file_name, doc_type, ex.*, raw_json AS extracted_json
FROM (
  SELECT file_name, doc_type, from_json(resp.result, 'STRUCT<fund_name:STRING,lp_name:STRING,period_end:STRING,currency:STRING,capital_commitment:DOUBLE,opening_balance:DOUBLE,contributions:DOUBLE,distributions:DOUBLE,management_fee:DOUBLE,unrealized_gain:DOUBLE,preferred_return:DOUBLE,closing_balance:DOUBLE,remaining_unfunded:DOUBLE>') AS ex, resp.result AS raw_json
  FROM (
    SELECT file_name, doc_type,
      ai_query('databricks-meta-llama-3-3-70b-instruct', CONCAT('You are a fund-administration data extraction engine. From the capital account statement below, return ONLY a JSON object with exactly these keys:
- fund_name: full legal fund name
- lp_name: the Limited Partner / investor this statement is for
- period_end: the period-end / ''as of'' date, as ISO YYYY-MM-DD
- currency: 3-letter ISO currency code
- capital_commitment: the LP''s total capital commitment
- opening_balance: opening / beginning capital account balance for the period
- contributions: capital contributions during the period (positive magnitude)
- distributions: distributions during the period (positive magnitude, 0 if none)
- management_fee: management fee charged during the period (positive magnitude)
- unrealized_gain: unrealized gain or loss allocated during the period (negative if a loss)
- preferred_return: preferred return accrued during the period (positive magnitude)
- closing_balance: closing / ending capital account balance for the period
- remaining_unfunded: remaining unfunded commitment
Rules: monetary amounts as plain numbers (no currency symbols, no thousands separators); dates as ISO YYYY-MM-DD; use null for any field not present. Return only the JSON object.

Document:
', text),
               responseFormat => '{"type":"json_object"}', failOnError => false,
               modelParameters => named_struct('temperature', CAST(0.0 AS DOUBLE))) AS resp
    FROM `fund_ops`.`silver`.`parsed_docs` WHERE doc_type = 'capital_account'
  )
)
