-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.

CREATE OR REPLACE TABLE `fund_ops`.`silver`.`capital_calls` AS
SELECT file_name, doc_type, ex.*, raw_json AS extracted_json
FROM (
  SELECT file_name, doc_type, from_json(resp.result, 'STRUCT<fund_name:STRING,call_number:STRING,notice_date:STRING,due_date:STRING,total_called:DOUBLE,currency:STRING,investment_amount:DOUBLE,management_fee:DOUBLE,fund_expenses:DOUBLE,commitment_base:DOUBLE,mgmt_fee_rate:DOUBLE,num_limited_partners:INT>') AS ex, resp.result AS raw_json
  FROM (
    SELECT file_name, doc_type,
      ai_query('databricks-meta-llama-3-3-70b-instruct', CONCAT('You are a fund-administration data extraction engine. From the capital call notice below, return ONLY a JSON object with exactly these keys:
- fund_name: full legal fund name
- call_number: the capital call / drawdown number
- notice_date: date the notice is dated, as ISO YYYY-MM-DD
- due_date: payment due date, as ISO YYYY-MM-DD
- total_called: total capital called in THIS notice (a single number)
- currency: 3-letter ISO currency code
- investment_amount: portion of the call for investments/acquisitions
- management_fee: the management fee AMOUNT in this call (not the rate)
- fund_expenses: fund expenses portion of the call
- commitment_base: AGGREGATE total fund commitments used as the management-fee base - one total number, never a per-LP list
- mgmt_fee_rate: annual management fee rate as a percent number, e.g. 2.0
- num_limited_partners: count of LPs in the call schedule
Rules: monetary amounts as plain numbers (no currency symbols, no thousands separators); dates as ISO YYYY-MM-DD; use null for any field not present. Return only the JSON object.

Document:
', text),
               responseFormat => '{"type":"json_object"}', failOnError => false,
               modelParameters => named_struct('temperature', CAST(0.0 AS DOUBLE))) AS resp
    FROM `fund_ops`.`silver`.`parsed_docs` WHERE doc_type = 'capital_call'
  )
)
