-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.

CREATE OR REPLACE TABLE `fund_ops`.`silver`.`distributions` AS
SELECT file_name, doc_type, ex.*, raw_json AS extracted_json
FROM (
  SELECT file_name, doc_type, from_json(resp.result, 'STRUCT<fund_name:STRING,distribution_number:STRING,distribution_date:STRING,distribution_type:STRING,total_proceeds:DOUBLE,currency:STRING,return_of_capital:DOUBLE,preferred_return:DOUBLE,gp_catchup:DOUBLE,residual_split:DOUBLE,gp_carry_total:DOUBLE,num_limited_partners:INT>') AS ex, resp.result AS raw_json
  FROM (
    SELECT file_name, doc_type,
      ai_query('databricks-meta-llama-3-3-70b-instruct', CONCAT('You are a fund-administration data extraction engine. From the distribution notice below, return ONLY a JSON object with exactly these keys:
- fund_name: full legal fund name
- distribution_number: the distribution notice number (use 1 for a single/final distribution if unnumbered)
- distribution_date: distribution date, as ISO YYYY-MM-DD
- distribution_type: one of return_of_capital, income, realized_gain, tax, final, gp_carry
- total_proceeds: total distributable proceeds in this notice (a single number)
- currency: 3-letter ISO currency code
- return_of_capital: Tier 1 return-of-capital AMOUNT (a money value)
- preferred_return: Tier 2 preferred / hurdle return AMOUNT in money - NOT a rate, percentage or MOIC multiple
- gp_catchup: Tier 3 GP catch-up AMOUNT in money
- residual_split: Tier 4 residual / carry split AMOUNT in money
- gp_carry_total: total carried interest AMOUNT paid to the GP
- num_limited_partners: count of LPs in the distribution schedule
Rules: monetary amounts as plain numbers (no currency symbols, no thousands separators); dates as ISO YYYY-MM-DD; use null for any field not present. Return only the JSON object.

Document:
', text),
               responseFormat => '{"type":"json_object"}', failOnError => false,
               modelParameters => named_struct('temperature', CAST(0.0 AS DOUBLE))) AS resp
    FROM `fund_ops`.`silver`.`parsed_docs` WHERE doc_type = 'distribution'
  )
)
