-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.

CREATE OR REPLACE TABLE `fund_ops`.`silver`.`validation_results` AS
SELECT file_name, doc_type, 'total_called_positive' AS check_name, 'error' AS severity,
  CASE WHEN NOT (total_called IS NOT NULL) THEN NULL ELSE (total_called > 0) END AS passed,
  CASE WHEN NOT (total_called IS NOT NULL) THEN 'n/a' ELSE concat('total_called=', total_called) END AS detail
FROM `fund_ops`.`silver`.`capital_calls`
UNION ALL
SELECT file_name, doc_type, 'line_items_reconcile' AS check_name, 'warning' AS severity,
  CASE WHEN NOT (investment_amount IS NOT NULL AND management_fee IS NOT NULL AND fund_expenses IS NOT NULL AND total_called IS NOT NULL) THEN NULL ELSE (abs((investment_amount+management_fee+fund_expenses) - total_called) <= 0.01*total_called) END AS passed,
  CASE WHEN NOT (investment_amount IS NOT NULL AND management_fee IS NOT NULL AND fund_expenses IS NOT NULL AND total_called IS NOT NULL) THEN 'n/a' ELSE concat('components=', round(investment_amount+management_fee+fund_expenses,0), ' vs total=', total_called) END AS detail
FROM `fund_ops`.`silver`.`capital_calls`
UNION ALL
SELECT file_name, doc_type, 'dates_ordered' AS check_name, 'warning' AS severity,
  CASE WHEN NOT (try_to_date(notice_date) IS NOT NULL AND try_to_date(due_date) IS NOT NULL) THEN NULL ELSE (try_to_date(due_date) >= try_to_date(notice_date)) END AS passed,
  CASE WHEN NOT (try_to_date(notice_date) IS NOT NULL AND try_to_date(due_date) IS NOT NULL) THEN 'n/a' ELSE concat(notice_date, ' -> ', due_date) END AS detail
FROM `fund_ops`.`silver`.`capital_calls`
UNION ALL
SELECT file_name, doc_type, 'call_within_commitments' AS check_name, 'warning' AS severity,
  CASE WHEN NOT (total_called IS NOT NULL AND commitment_base IS NOT NULL) THEN NULL ELSE (total_called <= commitment_base) END AS passed,
  CASE WHEN NOT (total_called IS NOT NULL AND commitment_base IS NOT NULL) THEN 'n/a' ELSE concat('called=', total_called, ' base=', commitment_base) END AS detail
FROM `fund_ops`.`silver`.`capital_calls`
UNION ALL
SELECT file_name, doc_type, 'fee_rate_plausible' AS check_name, 'info' AS severity,
  CASE WHEN NOT (mgmt_fee_rate IS NOT NULL) THEN NULL ELSE (mgmt_fee_rate > 0 AND mgmt_fee_rate <= 5) END AS passed,
  CASE WHEN NOT (mgmt_fee_rate IS NOT NULL) THEN 'n/a' ELSE concat('rate=', mgmt_fee_rate, '%') END AS detail
FROM `fund_ops`.`silver`.`capital_calls`
UNION ALL
SELECT file_name, doc_type, 'total_proceeds_positive' AS check_name, 'error' AS severity,
  CASE WHEN NOT (total_proceeds IS NOT NULL) THEN NULL ELSE (total_proceeds > 0) END AS passed,
  CASE WHEN NOT (total_proceeds IS NOT NULL) THEN 'n/a' ELSE concat('total_proceeds=', total_proceeds) END AS detail
FROM `fund_ops`.`silver`.`distributions`
UNION ALL
SELECT file_name, doc_type, 'waterfall_reconciles' AS check_name, 'warning' AS severity,
  CASE WHEN NOT (return_of_capital IS NOT NULL AND preferred_return IS NOT NULL AND gp_catchup IS NOT NULL AND residual_split IS NOT NULL AND total_proceeds IS NOT NULL) THEN NULL ELSE (abs((return_of_capital+preferred_return+gp_catchup+residual_split) - total_proceeds) <= 0.01*total_proceeds) END AS passed,
  CASE WHEN NOT (return_of_capital IS NOT NULL AND preferred_return IS NOT NULL AND gp_catchup IS NOT NULL AND residual_split IS NOT NULL AND total_proceeds IS NOT NULL) THEN 'n/a' ELSE concat('tiers=', round(return_of_capital+preferred_return+gp_catchup+residual_split,0), ' vs total=', total_proceeds) END AS detail
FROM `fund_ops`.`silver`.`distributions`
UNION ALL
SELECT file_name, doc_type, 'amounts_non_negative' AS check_name, 'error' AS severity,
  CASE WHEN NOT (true) THEN NULL ELSE (coalesce(return_of_capital,0) >= 0 AND coalesce(preferred_return,0) >= 0 AND coalesce(gp_catchup,0) >= 0 AND coalesce(residual_split,0) >= 0 AND coalesce(gp_carry_total,0) >= 0) END AS passed,
  CASE WHEN NOT (true) THEN 'n/a' ELSE 'tier amounts >= 0' END AS detail
FROM `fund_ops`.`silver`.`distributions`
UNION ALL
SELECT file_name, doc_type, 'carry_within_proceeds' AS check_name, 'warning' AS severity,
  CASE WHEN NOT (gp_carry_total IS NOT NULL AND total_proceeds IS NOT NULL) THEN NULL ELSE (gp_carry_total <= total_proceeds) END AS passed,
  CASE WHEN NOT (gp_carry_total IS NOT NULL AND total_proceeds IS NOT NULL) THEN 'n/a' ELSE concat('carry=', gp_carry_total, ' proceeds=', total_proceeds) END AS detail
FROM `fund_ops`.`silver`.`distributions`
