#!/usr/bin/env python
"""Generate the Databricks Asset Bundle's SQL task files from pipeline_sql.

Run this whenever the pipeline SQL changes so the deployable Job stays in lockstep
with the locally-tested transformations. Outputs to resources/sql/.
"""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import fundops_lib as fo  # noqa: E402
import pipeline_sql as ps  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "resources" / "sql"


def main() -> int:
    ns = fo.load_namespace()
    cc, di = ps.load_schema("capital_call"), ps.load_schema("distribution")
    ca = ps.load_schema("capital_account")
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "01_parse.sql": ps.parse_sql(ns),
        "02_extract_capital_calls.sql": ps.extract_primary_sql(ns, "capital_call", cc, "capital_calls"),
        "02_extract_distributions.sql": ps.extract_primary_sql(ns, "distribution", di, "distributions"),
        "02_extract_capital_accounts.sql": ps.extract_primary_sql(ns, "capital_account", ca, "capital_accounts"),
        "02_classify.sql": ps.classify_sql(ns),
        "03_validate.sql": ps.validate_sql(ns),
    }
    header = "-- AUTO-GENERATED by setup/gen_dab.py from pipeline_sql.py. Do not edit by hand.\n\n"
    for name, sql in files.items():
        (OUT / name).write_text(header + sql + "\n")
        print(f"  wrote resources/sql/{name} ({len(sql)} chars)")
    print(f"generated {len(files)} SQL task files for the bundle namespace {ns['catalog']}.{ns['silver_schema']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
